config/routes.rb
Rails.application.routes.draw do
  get 'home/home'

  # get 'invoice_payment_scheduels/index'

  # get 'invoice_payment_scheduels/new'

  # get 'invoice_payment_scheduels/create'

  # get 'invoice_payment_scheduels/edit'

  # get 'invoice_payment_scheduels/update'

  # get 'invoice_payment_scheduels/destroy'

  # get 'invoices/index'

  # get 'invoices/new'

  # get 'invoices/create'

  # get 'invoices/edit'

  # get 'invoices/update'

  # get 'invoices/destroy'

  # get 'job_orders/index'

  # get 'job_orders/new'

  # get 'job_orders/create'

  # get 'job_orders/edit'

  # get 'job_orders/update'

  # get 'job_orders/destroy'

  # get 'daily_production_input/index'

  # get 'daily_production_input/new'

  # get 'daily_production_input/create'

  # get 'daily_production_input/edit'

  # get 'daily_production_input/update'

  # get 'daily_production_input/destroy'

  # get 'raw_material_warehouse/index'

  # get 'raw_material_warehouse/new'

  # get 'raw_material_warehouse/create'

  # get 'raw_material_warehouse/edit'

  # get 'raw_material_warehouse/update'

  # get 'raw_material_warehouse/destroy'

  # get 'categories/index'

  # get 'categories/new'

  # get 'categories/create'

  # get 'categories/edit'

  # get 'categories/update'

  # get 'categories/destroy'

  # get 'carpet_data/index'

  # get 'carpet_data/new'

  # get 'carpet_data/create'

  # get 'carpet_data/edit'

  # get 'carpet_data/update'

  # get 'carpet_data/destroy'

  # get 'suppliers/index'

  # get 'suppliers/new'

  # get 'suppliers/create'

  # get 'suppliers/edit'

  # get 'suppliers/update'

  # get 'suppliers/destroy'

  # get 'workshops/index'

  # get 'workshops/new'

  # get 'workshops/create'

  # get 'workshops/edit'

  # get 'workshops/update'

  # get 'workshops/destroy'

  # get 'looms/index'

  # get 'looms/new'

  # get 'looms/create'

  # get 'looms/edit'

  # get 'looms/update'

  # get 'looms/destroy'

  # get 'workers/index'

  # get 'workers/new'

  # get 'workers/create'

  # get 'workers/edit'

  # get 'workers/update'

  # get 'workers/destroy'

  # get 'locations/index'

  # get 'locations/new'

  # get 'locations/create'

  # get 'locations/edit'

  # get 'locations/update'

  # get 'locations/destroy'

  # get 'showrooms/index'

  # get 'showrooms/new'

  # get 'showrooms/create'

  # get 'showrooms/edit'

  # get 'showrooms/update'

  # get 'showrooms/destroy'
  resources :showrooms,:locations, :workshops,:looms,:carpet_data,:categories,:invoices,:raw_material_warehouses,:workers,:job_orders,:suppliers,:main_designes,
            :invoice_payment_scheduels,:daily_production_inputs  
    root "home#home"
    # root "locations#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/carpet_datum.rb
class CarpetDatum < ApplicationRecord
	has_many :carpetmaterials
	has_many :raw_material_warehouses, through: :carpetmaterials
end

app/models/carpetmaterial.rb
class Carpetmaterial < ApplicationRecord
	belongs_to :carpet_datum
	belongs_to :raw_material_warehouse
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/job_order.rb
class JobOrder < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
	has_many :workshops
end

app/models/loom.rb
class Loom < ApplicationRecord
	  belongs_to :workshop

end

app/models/main_designe.rb
class MainDesigne < ApplicationRecord
end

app/models/purchase_request.rb
class PurchaseRequest < ApplicationRecord
end

app/models/showroom.rb
class Showroom < ApplicationRecord
	validates :name, :presence => true

end

app/models/supplier.rb
class Supplier < ApplicationRecord
end

app/models/worker.rb
class Worker < ApplicationRecord
end

app/models/workshop.rb
class Workshop < ApplicationRecord
	has_many :looms
	belongs_to :location
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  def index
    @workshops= Workshop.all
    @location=Location.all.map{|u| [u.name]}

  end

  def new
    @location_options = Location.all.map{ |u| [ u.name, u.id ] }
    @workshop= Workshop.new

  end

  def create
    @workshop=Workshop.new(workshops_params)
    if @workshop.save
      redirect_to(:action=>'index')#
    else
      render('new')
    end
  end

  def edit
    @location_options = Workshop.all.map{ |u| [ u.name, u.id ] }
    @workshop = Workshop.find(params[:id])
  end

  def update
    @workshop = Workshop.find(params[:id])
    if @workshop.update(workshops_params)
      redirect_to workshops_path
    else
      render 'edit'
    end
  end

  def destroy
    @workshop = Workshop.find(params[:id])
    @workshop.destroy
    redirect_to workshops_path
  end

  private
    def workshops_params
      params.require(:workshop).permit(:name,:location_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/looms_helper.rb
module LoomsHelper
end

app/helpers/showrooms_helper.rb
module ShowroomsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/workshops/_form.html.erb
 <%= form_for @workshop, :html => {:class => "form-horizontal center"} do |f| %>
  <% if @workshop.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@workshop.errors.count, "error") %> prohibited
        this workshop from being saved:
      </h2>
      <ul>
        <% @workshop.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
        <%= f.label :name, "اسم الورشه:", class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
       <%= f.label "المنطقه:", class: "col-md-4 control-label" %>
       <div class="col-md-8">
          <%= f.select(:location_id, @location_options)%>
        </div>
      </div>
      <%= f.submit "حفظ", class: "btn btn-default btn-primary" %>   
 <% end %>

app/views/workshops/edit.html.erb
<h2>تعديل بيانات الورشه</h2>

<%= render "workshops/form" %> 
<%= link_to 'عوده', workshops_path %>

app/views/workshops/index.html.erb
 <div class="page-header" dir="rtl">
    <h1>الورشه</h1>


</div>

<table class="table table-striped table-bordered table-condensed" dir="rtl">
<thead>
<tr>
  <th colspan="1" class="center">اسم الورشه</th>
  <th colspan="1" class="center">المنطقه</th>
  <th colspan="1" class="action">Actions</th>
  <th></th>
</tr>
</thead>
<tbody>
    <% unless @workshops.empty? %>
    <% @workshops.each do |workshop| %>
      <tr>
        <td><%= workshop.name %></td>
        <td><%= workshop.location.name %></td>        
        <td><%= link_to 'تعديل', edit_workshop_path(workshop) %>
        <%= link_to 'مسح', workshop_path(workshop),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
        </td>
        <td></td>
      </tr>
    <% end %>
    <% end %>

</tbody>
</table>
  <div class="contextual">
    <%= link_to(new_workshop_path, class: "btn btn-success") do %>
      اضافه ورشه جديده<i class="icon-plus icon-white"></i>
    <% end %>
  </div>

app/views/workshops/new.html.erb
<h2>اضافه ورشه</h2>

<%= render "workshops/form" %>